### ISSUE TITLE
check_rancher2 not returning data through Nagios

### ISSUE THREAD

**Issue by JJinMaine** [Napsty/check_rancher2#2]
Hello!

I've been able to get the check_rancher2 service check to correctly return data by executing it from the command line. I use the proper token, password and when I attempt to get info, everything works as expected:

![image](https://user-images.githubusercontent.com/25136285/64130306-8791af80-cd8f-11e9-9594-25438ee98d72.png)

However, when I attempt to run the same command through the Nagios (using Check_MK as a UI) wrapper, it never returns any data:

![image](https://user-images.githubusercontent.com/25136285/64130252-1ce07400-cd8f-11e9-9b0d-dc194885e15d.png)

I've tried putting parameters in quotes, I've tried using $USERX$ variables for the token and password, I've tried escaping values, etc, etc. I've tried a lot of different methods that have worked in my 10 years of doing Nagios to get this working, but I can't figure it out. 

Command definition:

![image](https://user-images.githubusercontent.com/25136285/64130367-d4758600-cd8f-11e9-83af-1e1c40c58b9a.png)

Service definition:

![image](https://user-images.githubusercontent.com/25136285/64130414-0f77b980-cd90-11e9-9380-88ac8f24f8ef.png)

Have you actually confirmed that you got it working in Nagios and not just Icinga? My only modification to the script was adding a "-k" to all the curl calls since I'm using a self-signed CA Cert chain for the HTTPS rancher endpoint. And like I said, everything works perfectly on the command line but when it's trying to run in Nagios itself, it doesn't return.

Thoughts?

**Comment by Napsty** [comment]
Hi, thanks for reporting.

I just installed a plain new installation of Nagios 4.4.5 and the plugin outputs the status just fine:

![image](https://user-images.githubusercontent.com/3702203/64154831-e14ab600-ce31-11e9-90eb-85fcae544e30.png)

Aren't you missing the `host_name` value in your service definition? Or did you black it out on purpose?

**Comment by Napsty** [comment]
By the way good hint for the `-k`. I think this should be made configurable using a parameter.

**Comment by Napsty** [comment]
@JJinMaine the plugin was improved to address these two issues (unrelated to your Nagios config). Please use the released version 1.2.0 or newer. Use the new `-s` parameter to allow self-signed certificates. I will update the official documentation on https://www.claudiokuenzler.com/monitoring-plugins/check_rancher2.php shortly.

**Comment by JJinMaine** [comment]
Hi @Napsty, Yes, I had blacked out the hostname in my post - I was calling it correctly. Even adding -s to the command and using the new version gets me the same result. I'll keep working on it, maybe get some extra debug enabled for the curl call. Thanks for the updates!

**Comment by Napsty** [comment]
Try to run the new plugin version. It should now return an UNKNOWN and indicate the used hostname. Maybe this hostname is somehow overwritten by something (a template maybe?). You can write me on ck@claudiokuenzler.com to debug this.
