### ISSUE TITLE
support for "Kubernetes Version: v1.20.8"

### ISSUE THREAD

**Issue by andreas-theswede** [Napsty/check_rancher2#23]
Hi does the check_rancher2 support Kubernetes Version: v1.20.8? 

We have five clusters and all are visible except for the cluster on Kubernetes Version: v1.20.8 the rest is on Kubernetes Version: v1.19.x

[root@ilop51 plugins]# ./check_rancher2.sh -H ilrancherha01 -S -U token-xxxxx -S -P xxxxxxxxx -t cluster
CHECK_RANCHER2 OK - All clusters (4) are healthy|'clusters_total'=4;;;; 'clusters_errors'=0;;;;

if I query a project directly I get 

 ./check_rancher2.sh -H ilrancherha01 -S -U token-xxxxx -S -P xxxxxxxxx -t workload -p c-4pfth:p-49bns
CHECK_RANCHER2 WARNING - No workloads found in project c-4pfth:p-49bns. 

//Andreas

**Comment by Napsty** [comment]
Yes, I have a Rancher 2 cluster with Kubernetes 1.20.8 running and the plugin works correctly. 
Maybe you have not deployed any workload in that particular project c-4pfth:p-49bns?
