### ISSUE TITLE
Cluster node check ignoring all nodes down state

### ISSUE THREAD

**Issue by txj-xyz** [Napsty/check_rancher2#26]
Currently my entire cluster is down and all of the nodes along with it, the script itself does not care if the cluster is entirely down it still thinks that the cluster state is healthy, is there something I am doing wrong?

Currently I am attempting to monitor if a cluster has a broken node inside of it, and this one is down with 6 nodes, can you point me in the right direction?

![image](https://user-images.githubusercontent.com/7461476/135522497-aa52b5ee-b7bf-4fa7-891e-c0746d05fdec.png)

**Comment by txj-xyz** [comment]
Here is the Cluster Management page as well (Running Rancher 2.6.0)

![image](https://user-images.githubusercontent.com/7461476/135522955-c1ad1bfc-eab6-451a-a5e0-1b9490a4d007.png)

**Comment by Napsty** [comment]
Thanks for the report.

The Rancher API still seems to work. It interprets all nodes as "Active", as you can see in both the plugin output and in Rancher's UI. The plugin does nothing else than pulling the node statuses from the Rancher API.

Now the question is what exactly is down. If the cluster was completely down, you wouldn't even be able to see the nodes of this cluster. 

How is your cluster "flexpod-portland" showing up in the Home Dashboard (https://rancher.example.com/dashboard/home)?

**Comment by Napsty** [comment]
What does the cluster specific check say?

`-t cluster -c c-p665k`

**Comment by txj-xyz** [comment]
@Napsty Responds with

```
CHECK_RANCHER2 OK - Cluster flexcloud-portland is healthy|'cluster_healthy'=1;;;; 'component_errors'=0;;;; 'cpu'=2620;;;;18000 'memory'=1593835520B;;;;101032058880 'pods'=30;;;;330
```

**Comment by txj-xyz** [comment]
All nodes in the cluster are offline for this test as well, powered all of the VMs off.

**Comment by Napsty** [comment]
I am afraid this needs to be analyzed on API level. Maybe it's even a bug in the API itself, it would then make sense to open an issue in the Rancher repos. 
Would it be possible to give me access to the API of this particular Rancher installation? Please contact me directly https://www.claudiokuenzler.com/about/

**Comment by txj-xyz** [comment]
This is a closed network, unfortunately not. I've taken a look through the API responses and it appears that the API object its attempting to look at does not even change states.

I'll check in with the Rancher Devs.

**Comment by txj-xyz** [comment]
This is possible to edit and look at a different response but I haven't taken the liberty yet to make my own fork or pull request.

A bit busy recently.

**Comment by txj-xyz** [comment]
Any update on this?

**Comment by Napsty** [comment]
I finally got a few minutes to look into this. The json output clearly shows the cluster "flexcloud-portland" in error state. So it's a bug in the plugin, the plugin should detect this.

**Comment by Napsty** [comment]
@txj-xyz can you please try with this version:
https://raw.githubusercontent.com/Napsty/check_rancher2/1.7.1/check_rancher2.sh
Please check both `-t cluster` with and without the specific cluster id.

On my (local) test with using the JSON file you sent me it seems to work.

Before bugfix:

```
$ ./check_rancher2.sh -H asdfasfasf -U asdasdfaf -P asfasdf -t cluster
CHECK_RANCHER2 OK - All clusters (20) are healthy|'clusters_total'=20;;;; 'clusters_errors'=0;;;;
```

With bugfix:

```
$ ./check_rancher2.sh -H asdfasfasf -U asdasdfaf -P asfasdf -t cluster
CHECK_RANCHER2 CRITICAL - cluster flexcloud-portland is in error state -|'clusters_total'=20;;;; 'clusters_errors'=1;;;;
```

**Comment by Napsty** [comment]
@txj-xyz were you able to test?

**Comment by txj-xyz** [comment]
@Napsty Testing now.

**Comment by txj-xyz** [comment]
This is working now.

Thank you so much for the fixes.

**Comment by txj-xyz** [comment]
Command used to check for single node failure
```
./check_rancher4.sh -H myipaddress -S -s -U userhere -P yespasswordhere -t cluster
```
Response
`CHECK_RANCHER2 OK - All clusters (23) are healthy|'clusters_total'=23;;;; 'clusters_errors'=0;;;;`


---

took an ETC-D node offline, and response with same command.

`CHECK_RANCHER2 CRITICAL - cluster flexcloud-portland is in error state -|'clusters_total'=23;;;; 'clusters_errors'=1;;;;`
