### ISSUE TITLE
Ignoring statuses in workloads

### ISSUE THREAD

**Issue by dbrau** [Napsty/check_rancher2#29]
Hello all,
we use the plugin for our monitoring environment and in version 1.3.0 the option to ignore some status(es) of nodes was integrated. 
I would like to do this also for workloads. Workloads in status "initializing" should not be shown directly as critical. 
Is it possible to implement this function? I haven't found a corresponding parameter yet. "-i" refers only to the nodes. 

Many thanks already
Best regards

**Comment by Napsty** [comment]
@dbrau Please try with https://raw.githubusercontent.com/Napsty/check_rancher2/issue-35/check_rancher2.sh. Should work.

Without `-i` parameter:

```
./check_rancher2.sh -H rancher.example.com -U token-xxxxx -P "secret" -S -t workload -p c-fctn6:p-2xg6v 
CHECK_RANCHER2 WARNING - 1 workload(s) in warning state: Workload efk-filebeat is updating - |'workloads_total'=3;;;; 'workloads_errors'=0;;;; 'workloads_warnings'=1;;;; 'workloads_paused'=0;;;; 'workloads_ignored'=0;;;;
```

With ignoring "updating" status:

```
./check_rancher2.sh -H rancher.example.com -U token-xxxxx -P "secret" -S -t workload -p c-fctn6:p-2xg6v -i updating
CHECK_RANCHER2 OK - All workloads (3) in project c-fctn6:p-2xg6v are healthy/active - Workload efk-filebeat is updating but ignored -|'workloads_total'=3;;;; 'workloads_errors'=0;;;; 'workloads_warnings'=0;;;; 'workloads_paused'=0;;;; 'workloads_ignored'=1;;;;
```
